name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_IktK5MTe8Mdybe6bQkwRh4Ah
          VERCEL_PROJECT_ID: prj_ZO1dVcEB6VpOFwCk42Pncs0Hdtuj
